// Generated by constraint-test-generator.zig.
// Fill in the TODOs with real constructions and assertions.
const std = @import("std");
const composer = @import("composer");
const harness = @import("harness.zig");
const graph = composer.schemas.graph;

test "Constraints c1_entropy_flow negative" {
    const proof = harness.Proof{
        .statement = "c1_entropy_flow rejects invalid construction.",
        .argument = "Input entropy is below the minimum required by the KDF.",
        .constraints = &[_]harness.ConstraintId{.c1_entropy_flow},
    };

    const cat = composer.catalog.DefaultCatalog;
    const kdf = composer.catalog.kdfs.HKDF_SHA256;
    const ctx = graph.DerivationContext{
        .schema_id = "Test",
        .protocol_id = "test",
        .suite_id = "suite",
        .transcript_hash = null,
        .message_id = null,
    };

    const values = [_]graph.Value{
        .{ .name = "seed", .entropy = .{ .min_entropy = 64 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "out", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf1" } },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const kdf_calls = [_]graph.KDFCall{
        .{
            .id = "kdf1",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "test/kdf1",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out",
            .out_ctx_kind = .transcript_bound,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .kdf_call = "kdf1" } }, .to = .{ .value = "out" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "out", .value = "out", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = kdf_calls[0..],
        .aead_ops = &[_]graph.AeadOp{},
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .c1_entropy_flow, .present);
}

test "Constraints c1_entropy_flow positive" {
    const proof = harness.Proof{
        .statement = "c1_entropy_flow accepts valid construction.",
        .argument = "Input entropy meets the minimum requirement for the KDF.",
        .constraints = &[_]harness.ConstraintId{ .overall_valid, .c1_entropy_flow },
    };

    const cat = composer.catalog.DefaultCatalog;
    const kdf = composer.catalog.kdfs.HKDF_SHA256;
    const ctx = graph.DerivationContext{
        .schema_id = "Test",
        .protocol_id = "test",
        .suite_id = "suite",
        .transcript_hash = null,
        .message_id = null,
    };

    const values = [_]graph.Value{
        .{ .name = "seed", .entropy = .{ .uniform = 256 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "out", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf1" } },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const kdf_calls = [_]graph.KDFCall{
        .{
            .id = "kdf1",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "test/kdf1",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out",
            .out_ctx_kind = .transcript_bound,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .kdf_call = "kdf1" } }, .to = .{ .value = "out" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "out", .value = "out", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = kdf_calls[0..],
        .aead_ops = &[_]graph.AeadOp{},
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .overall_valid, .present);
}

test "Constraints c2_domain_sep negative" {
    const proof = harness.Proof{
        .statement = "c2_domain_sep rejects invalid construction.",
        .argument = "Duplicate KDF labels violate domain separation.",
        .constraints = &[_]harness.ConstraintId{.c2_domain_sep},
    };

    const cat = composer.catalog.DefaultCatalog;
    const kdf = composer.catalog.kdfs.HKDF_SHA256;
    const ctx = graph.DerivationContext{
        .schema_id = "Test",
        .protocol_id = "test",
        .suite_id = "suite",
        .transcript_hash = null,
        .message_id = null,
    };

    const values = [_]graph.Value{
        .{ .name = "seed", .entropy = .{ .uniform = 256 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "out1", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf1" } },
        .{ .name = "out2", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf2" } },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const kdf_calls = [_]graph.KDFCall{
        .{
            .id = "kdf1",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "dup",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out1",
            .out_ctx_kind = .transcript_bound,
        },
        .{
            .id = "kdf2",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "dup",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out2",
            .out_ctx_kind = .transcript_bound,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .kdf_call = "kdf1" } }, .to = .{ .value = "out1" } },
        .{ .from = .{ .direct = .{ .kdf_call = "kdf2" } }, .to = .{ .value = "out2" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "out1", .value = "out1", .kind = .value, .public = false },
        .{ .name = "out2", .value = "out2", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = kdf_calls[0..],
        .aead_ops = &[_]graph.AeadOp{},
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .c2_domain_sep, .present);
}

test "Constraints c2_domain_sep positive" {
    const proof = harness.Proof{
        .statement = "c2_domain_sep accepts valid construction.",
        .argument = "Distinct KDF labels preserve domain separation.",
        .constraints = &[_]harness.ConstraintId{ .overall_valid, .c2_domain_sep },
    };

    const cat = composer.catalog.DefaultCatalog;
    const kdf = composer.catalog.kdfs.HKDF_SHA256;
    const ctx = graph.DerivationContext{
        .schema_id = "Test",
        .protocol_id = "test",
        .suite_id = "suite",
        .transcript_hash = null,
        .message_id = null,
    };

    const values = [_]graph.Value{
        .{ .name = "seed", .entropy = .{ .uniform = 256 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "out1", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf1" } },
        .{ .name = "out2", .entropy = kdf.outputEntropy(.key, 256, .transcript_bound), .timing = kdf.timing, .secret = true, .source = .{ .kdf_call = "kdf2" } },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const kdf_calls = [_]graph.KDFCall{
        .{
            .id = "kdf1",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "kdf/one",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out1",
            .out_ctx_kind = .transcript_bound,
        },
        .{
            .id = "kdf2",
            .kdf_name = kdf.name,
            .inputs = &[_]graph.ValueRef{.{ .direct = .{ .value = "seed" } }},
            .in_required_ctx_kind = .none,
            .label = "kdf/two",
            .ctx = ctx,
            .scope = .session,
            .use = .key,
            .out_bits = 256,
            .out_name = "out2",
            .out_ctx_kind = .transcript_bound,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .kdf_call = "kdf1" } }, .to = .{ .value = "out1" } },
        .{ .from = .{ .direct = .{ .kdf_call = "kdf2" } }, .to = .{ .value = "out2" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "out1", .value = "out1", .kind = .value, .public = false },
        .{ .name = "out2", .value = "out2", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = kdf_calls[0..],
        .aead_ops = &[_]graph.AeadOp{},
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .overall_valid, .present);
}

test "Constraints c3_nonce_discipline negative" {
    const proof = harness.Proof{
        .statement = "c3_nonce_discipline rejects invalid construction.",
        .argument = "Nonce provided directly rather than derived from message-scoped KDF.",
        .constraints = &[_]harness.ConstraintId{.c3_nonce_discipline},
    };

    const cat = composer.catalog.DefaultCatalog;
    const aead = composer.catalog.aeads.AES_256_GCM;

    const values = [_]graph.Value{
        .{ .name = "key", .entropy = .{ .uniform = 256 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "nonce", .entropy = .{ .uniform = 96 }, .timing = .constant_time, .secret = false, .source = .input },
        .{ .name = "aad", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .input },
        .{ .name = "plaintext", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "ct", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .{ .aead_op = .{ .op_id = "aead_seal", .output_kind = .ciphertext } } },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const aead_ops = [_]graph.AeadOp{
        .{
            .id = "aead_seal",
            .aead_name = aead.name,
            .kind = .seal,
            .key = .{ .value = "key" },
            .nonce = .{ .value = "nonce" },
            .aad = .{ .value = "aad" },
            .plaintext = .{ .value = "plaintext" },
            .ciphertext = null,
            .ct_out = "ct",
            .pt_out = null,
            .failure_out = null,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .aead_op = "aead_seal" } }, .to = .{ .value = "ct" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "ciphertext", .value = "ct", .kind = .value, .public = true },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = &[_]graph.KDFCall{},
        .aead_ops = aead_ops[0..],
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .c3_nonce_discipline, .present);
}

test "Constraints c3_nonce_discipline positive" {
    const proof = harness.Proof{
        .statement = "c3_nonce_discipline accepts valid construction.",
        .argument = "Nonce derived from message-scoped KDF with message_id and message-bound context.",
        .constraints = &[_]harness.ConstraintId{.c3_nonce_discipline},
    };

    const cat = composer.catalog.DefaultCatalog;
    var product = composer.types.contracts.Product{
        .name = "HPKE-KEMDEM",
        .protocol_id = "hpke",
        .requirements = .{ .key_committing = false },
    };
    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "kem", .primitive = .{ .kem = &composer.catalog.kems.ML_KEM_768 } },
        .{ .slot_name = "kdf", .primitive = .{ .kdf = &composer.catalog.kdfs.HKDF_SHA256 } },
        .{ .slot_name = "aead", .primitive = .{ .aead = &composer.catalog.aeads.AES_256_GCM } },
    };

    var g = try composer.schemas.kem_dem.expandKEMDEMSeal(std.testing.allocator, bindings, &product, 0);
    defer graph.freeGraph(std.testing.allocator, &g);

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, product.requirements, .c3_nonce_discipline, .absent);
}

test "Constraints c4_failure_consistency negative" {
    const proof = harness.Proof{
        .statement = "c4_failure_consistency rejects failure reaching secret output.",
        .argument = "Failure output flows to a secret value without hitting reject boundary.",
        .constraints = &[_]harness.ConstraintId{.c4_failure_consistency},
    };

    const cat = composer.catalog.DefaultCatalog;
    const kem = composer.catalog.kems.ML_KEM_768;

    const values = [_]graph.Value{
        .{ .name = "sk", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "ct", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .input },
        .{ .name = "ss_success", .entropy = kem.ss_entropy_success, .timing = kem.timing, .secret = true, .source = .{ .kem_op = .{ .op_id = "kem_decap", .output_kind = .shared_secret_success } } },
        .{ .name = "ss_failure", .entropy = kem.ss_entropy_failure, .timing = kem.timing, .secret = true, .source = .{ .kem_op = .{ .op_id = "kem_decap", .output_kind = .shared_secret_failure } } },
        .{ .name = "leaked_key", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = true, .source = .structural },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const kem_ops = [_]graph.KemOp{
        .{
            .id = "kem_decap",
            .kem_name = kem.name,
            .kind = .decap,
            .inputs = &[_]graph.Ref{ .{ .value = "sk" }, .{ .value = "ct" } },
            .ct_out = null,
            .ss_success_out = "ss_success",
            .ss_failure_out = "ss_failure",
            .out_ctx_kind_success = .transcript_bound,
            .out_ctx_kind_failure = .ciphertext_bound,
        },
    };
    const edges = [_]graph.FlowEdge{
        .{ .from = .{ .direct = .{ .value = "ss_failure" } }, .to = .{ .value = "leaked_key" } },
    };
    const outputs = [_]graph.Output{
        .{ .name = "leaked_key", .value = "leaked_key", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = kem_ops[0..],
        .kdf_calls = &[_]graph.KDFCall{},
        .aead_ops = &[_]graph.AeadOp{},
        .edges = edges[0..],
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .c4_failure_consistency, .present);
}

test "Constraints c4_failure_consistency positive" {
    const proof = harness.Proof{
        .statement = "c4_failure_consistency accepts failure paths terminating at reject boundary.",
        .argument = "Failure values flow only to reject boundary and not to secret outputs.",
        .constraints = &[_]harness.ConstraintId{ .overall_valid, .c4_failure_consistency },
    };

    const cat = composer.catalog.DefaultCatalog;
    var product = composer.types.contracts.Product{
        .name = "HybridKEM",
        .protocol_id = "hybrid",
        .requirements = .{ .key_committing = false },
    };
    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "classical", .primitive = .{ .kem = &composer.catalog.kems.X25519 } },
        .{ .slot_name = "pq", .primitive = .{ .kem = &composer.catalog.kems.ML_KEM_768 } },
        .{ .slot_name = "kdf", .primitive = .{ .kdf = &composer.catalog.kdfs.HKDF_SHA256 } },
    };

    var g = try composer.schemas.hybrid_kem.expandHybridKEMDecap(std.testing.allocator, bindings, &product);
    defer graph.freeGraph(std.testing.allocator, &g);

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, product.requirements, .overall_valid, .present);
}

test "Constraints c5_timing_chain negative" {
    const proof = harness.Proof{
        .statement = "c5_timing_chain warns on secret data-dependent timing.",
        .argument = "Secret values marked data-dependent should trigger timing warning.",
        .constraints = &[_]harness.ConstraintId{.c5_timing_chain},
    };

    const cat = composer.catalog.DefaultCatalog;

    const values = [_]graph.Value{
        .{ .name = "secret", .entropy = .{ .uniform = 0 }, .timing = .data_dependent, .secret = true, .source = .input },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const outputs = [_]graph.Output{
        .{ .name = "secret", .value = "secret", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = &[_]graph.KDFCall{},
        .aead_ops = &[_]graph.AeadOp{},
        .edges = &[_]graph.FlowEdge{},
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .c5_timing_chain, .present);
}

test "Constraints c5_timing_chain positive" {
    const proof = harness.Proof{
        .statement = "c5_timing_chain accepts secret values with constant-time timing.",
        .argument = "Secret values marked constant-time should not trigger warnings.",
        .constraints = &[_]harness.ConstraintId{ .overall_valid, .c5_timing_chain },
    };

    const cat = composer.catalog.DefaultCatalog;

    const values = [_]graph.Value{
        .{ .name = "secret", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = true, .source = .input },
        .{ .name = "reject_boundary", .entropy = .{ .uniform = 0 }, .timing = .constant_time, .secret = false, .source = .structural },
    };
    const outputs = [_]graph.Output{
        .{ .name = "secret", .value = "secret", .kind = .value, .public = false },
        .{ .name = "reject", .value = "reject_boundary", .kind = .reject_boundary, .public = false },
    };

    const g = graph.CompositionGraph{
        .values = values[0..],
        .kem_ops = &[_]graph.KemOp{},
        .kdf_calls = &[_]graph.KDFCall{},
        .aead_ops = &[_]graph.AeadOp{},
        .edges = &[_]graph.FlowEdge{},
        .outputs = outputs[0..],
    };

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, .{}, .overall_valid, .present);
}

test "Constraints c6_key_commitment negative" {
    const proof = harness.Proof{
        .statement = "c6_key_commitment rejects non-key-committing AEAD when required.",
        .argument = "AES-256-GCM is not key-committing; product requires commitment.",
        .constraints = &[_]harness.ConstraintId{.c6_key_commitment},
    };

    const cat = composer.catalog.DefaultCatalog;
    var product = composer.types.contracts.Product{
        .name = "HPKE-KEMDEM",
        .protocol_id = "hpke",
        .requirements = .{ .key_committing = true },
    };
    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "kem", .primitive = .{ .kem = &composer.catalog.kems.ML_KEM_768 } },
        .{ .slot_name = "kdf", .primitive = .{ .kdf = &composer.catalog.kdfs.HKDF_SHA256 } },
        .{ .slot_name = "aead", .primitive = .{ .aead = &composer.catalog.aeads.AES_256_GCM } },
    };

    var g = try composer.schemas.kem_dem.expandKEMDEMSeal(std.testing.allocator, bindings, &product, 0);
    defer graph.freeGraph(std.testing.allocator, &g);

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, product.requirements, .c6_key_commitment, .present);
}

test "Constraints c6_key_commitment positive" {
    const proof = harness.Proof{
        .statement = "c6_key_commitment accepts when product does not require it.",
        .argument = "Key-commitment checks are skipped if the product requirement is false.",
        .constraints = &[_]harness.ConstraintId{ .overall_valid, .c6_key_commitment },
    };

    const cat = composer.catalog.DefaultCatalog;
    var product = composer.types.contracts.Product{
        .name = "HPKE-KEMDEM",
        .protocol_id = "hpke",
        .requirements = .{ .key_committing = false },
    };
    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "kem", .primitive = .{ .kem = &composer.catalog.kems.ML_KEM_768 } },
        .{ .slot_name = "kdf", .primitive = .{ .kdf = &composer.catalog.kdfs.HKDF_SHA256 } },
        .{ .slot_name = "aead", .primitive = .{ .aead = &composer.catalog.aeads.AES_256_GCM } },
    };

    var g = try composer.schemas.kem_dem.expandKEMDEMSeal(std.testing.allocator, bindings, &product, 0);
    defer graph.freeGraph(std.testing.allocator, &g);

    try harness.expectConstraint(proof, std.testing.allocator, &g, &cat, product.requirements, .overall_valid, .present);
}

test "Constraints w1_assumption_diversity warns on same-class KEMs" {
    const proof = harness.Proof{
        .statement = "w1_assumption_diversity warns when KEMs share assumption class.",
        .argument = "Two discrete-log KEMs violate diversity advisory.",
        .constraints = &[_]harness.ConstraintId{.w1_assumption_diversity},
    };

    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "classical", .primitive = .{ .kem = &composer.catalog.kems.X25519 } },
        .{ .slot_name = "classical2", .primitive = .{ .kem = &composer.catalog.kems.X25519 } },
    };

    try harness.expectW1(proof, bindings, true);
}

test "Constraints w1_assumption_diversity accepts mixed assumption classes" {
    const proof = harness.Proof{
        .statement = "w1_assumption_diversity does not warn when KEMs differ in class.",
        .argument = "Discrete-log and lattice KEMs satisfy the diversity advisory.",
        .constraints = &[_]harness.ConstraintId{.w1_assumption_diversity},
    };

    const bindings = &[_]composer.types.contracts.Binding{
        .{ .slot_name = "classical", .primitive = .{ .kem = &composer.catalog.kems.X25519 } },
        .{ .slot_name = "pq", .primitive = .{ .kem = &composer.catalog.kems.ML_KEM_768 } },
    };

    try harness.expectW1(proof, bindings, false);
}
