const std = @import("std");

pub const Mode = enum { fail };

pub const Options = struct {
    suite_name: []const u8 = "Constraints",
    harness_import: []const u8 = "harness.zig",
    harness_name: []const u8 = "harness",
    proof_fn: ?[]const u8 = null,
    constraint_type: ?[]const u8 = null,
    constraints: []const []const u8 = &.{},
    include_negative: bool = true,
    include_positive: bool = true,
    mode: Mode = .fail,
};

pub fn generate(allocator: std.mem.Allocator, options: Options) ![]const u8 {
    if (options.constraints.len == 0) return error.MissingConstraints;
    if (!options.include_negative and !options.include_positive) return error.NoTestsSelected;
    if (options.suite_name.len == 0) return error.EmptySuiteName;
    if (options.harness_name.len == 0) return error.EmptyHarnessName;
    if (options.harness_import.len == 0) return error.EmptyHarnessImport;

    for (options.constraints) |constraint| {
        if (!isValidIdentifier(constraint)) return error.InvalidConstraintId;
    }

    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);

    try appendHeader(&out, allocator, options);

    for (options.constraints) |constraint| {
        if (options.include_negative) {
            try appendTest(&out, allocator, options, constraint, .negative);
        }
        if (options.include_positive) {
            try appendTest(&out, allocator, options, constraint, .positive);
        }
    }

    return out.toOwnedSlice(allocator);
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    var options = Options{};
    var constraints_csv: ?[]const u8 = null;
    var out_path: ?[]const u8 = null;

    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        const arg = args[i];
        if (std.mem.eql(u8, arg, "--help")) {
            try printUsage(std.fs.File.stdout());
            return;
        } else if (std.mem.eql(u8, arg, "--constraints")) {
            i += 1;
            if (i >= args.len) return error.MissingConstraints;
            constraints_csv = args[i];
        } else if (std.mem.eql(u8, arg, "--out")) {
            i += 1;
            if (i >= args.len) return error.MissingOutPath;
            out_path = args[i];
        } else if (std.mem.eql(u8, arg, "--suite")) {
            i += 1;
            if (i >= args.len) return error.MissingSuiteName;
            options.suite_name = args[i];
        } else if (std.mem.eql(u8, arg, "--harness-import")) {
            i += 1;
            if (i >= args.len) return error.MissingHarnessImport;
            options.harness_import = args[i];
        } else if (std.mem.eql(u8, arg, "--harness-name")) {
            i += 1;
            if (i >= args.len) return error.MissingHarnessName;
            options.harness_name = args[i];
        } else if (std.mem.eql(u8, arg, "--proof-fn")) {
            i += 1;
            if (i >= args.len) return error.MissingProofFn;
            options.proof_fn = args[i];
        } else if (std.mem.eql(u8, arg, "--constraint-type")) {
            i += 1;
            if (i >= args.len) return error.MissingConstraintType;
            options.constraint_type = args[i];
        } else if (std.mem.eql(u8, arg, "--negative-only")) {
            options.include_positive = false;
        } else if (std.mem.eql(u8, arg, "--positive-only")) {
            options.include_negative = false;
        } else {
            return error.UnknownOption;
        }
    }

    if (constraints_csv == null) {
        try printUsage(std.fs.File.stdout());
        return error.MissingConstraints;
    }

    const constraints = try parseConstraints(allocator, constraints_csv.?);
    defer allocator.free(constraints);
    options.constraints = constraints;

    const output = try generate(allocator, options);
    defer allocator.free(output);

    if (out_path) |path| {
        if (std.mem.eql(u8, path, "-")) {
            try std.fs.File.stdout().writeAll(output);
            return;
        }
        var file = try std.fs.cwd().createFile(path, .{ .truncate = true });
        defer file.close();
        try file.writeAll(output);
        return;
    }

    try std.fs.File.stdout().writeAll(output);
}

const TestKind = enum { negative, positive };

fn appendHeader(out: *std.ArrayList(u8), allocator: std.mem.Allocator, options: Options) !void {
    try appendLine(out, allocator, "// Generated by constraint-test-generator.zig.");
    try appendLine(out, allocator, "// Fill in the TODOs with real constructions and assertions.");
    try appendLine(out, allocator, "const std = @import(\"std\");");
    try appendFmt(out, allocator, "const {s} = @import(\"{s}\");\n\n", .{
        options.harness_name,
        options.harness_import,
    });
}

fn appendTest(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    options: Options,
    constraint: []const u8,
    kind: TestKind,
) !void {
    const kind_label = if (kind == .negative) "negative" else "positive";
    const verb = if (kind == .negative) "rejects" else "accepts";
    const case_label = if (kind == .negative) "failing" else "passing";
    const construction_label = if (kind == .negative) "invalid" else "valid";

    try appendFmt(out, allocator, "test \"{s} {s} {s}\" {{\n", .{
        options.suite_name,
        constraint,
        kind_label,
    });

    try appendProof(out, allocator, options, constraint, verb, construction_label);

    try appendFmt(out, allocator, "    // TODO: construct a {s} case for {s}.\n\n", .{
        case_label,
        constraint,
    });

    switch (options.mode) {
        .fail => try appendLine(out, allocator, "    try std.testing.expect(false);"),
    }

    try appendLine(out, allocator, "}\n");
}

fn appendProof(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    options: Options,
    constraint: []const u8,
    verb: []const u8,
    construction_label: []const u8,
) !void {
    try appendSlice(out, allocator, "    const proof = ");
    try appendProofType(out, allocator, options);
    try appendLine(out, allocator, "{");
    try appendFmt(out, allocator, "        .statement = \"{s} {s} {s} construction.\",\n", .{
        constraint,
        verb,
        construction_label,
    });
    try appendFmt(out, allocator, "        .argument = \"TODO: justify why {s} {s} this case.\",\n", .{
        constraint,
        verb,
    });
    try appendSlice(out, allocator, "        .constraints = &[_]");
    try appendConstraintType(out, allocator, options);
    try appendFmt(out, allocator, "{{ .{s} }},\n", .{constraint});
    try appendLine(out, allocator, "    };");

    try appendSlice(out, allocator, "    try ");
    try appendProofFn(out, allocator, options);
    try appendSlice(out, allocator, "(proof, .");
    try appendSlice(out, allocator, constraint);
    try appendLine(out, allocator, ");\n");
}

fn appendProofFn(out: *std.ArrayList(u8), allocator: std.mem.Allocator, options: Options) !void {
    if (options.proof_fn) |proof_fn| {
        try appendSlice(out, allocator, proof_fn);
        return;
    }
    try appendFmt(out, allocator, "{s}.requireProofForConstraint", .{options.harness_name});
}

fn appendProofType(out: *std.ArrayList(u8), allocator: std.mem.Allocator, options: Options) !void {
    try appendFmt(out, allocator, "{s}.Proof", .{options.harness_name});
}

fn appendConstraintType(out: *std.ArrayList(u8), allocator: std.mem.Allocator, options: Options) !void {
    if (options.constraint_type) |constraint_type| {
        try appendSlice(out, allocator, constraint_type);
        return;
    }
    try appendFmt(out, allocator, "{s}.ConstraintId", .{options.harness_name});
}

fn parseConstraints(allocator: std.mem.Allocator, csv: []const u8) ![]const []const u8 {
    var list = std.ArrayList([]const u8).empty;
    errdefer list.deinit(allocator);

    var it = std.mem.splitScalar(u8, csv, ',');
    while (it.next()) |raw| {
        const token = std.mem.trim(u8, raw, " \t\r\n");
        if (token.len == 0) return error.InvalidConstraintId;
        if (!isValidIdentifier(token)) return error.InvalidConstraintId;
        try list.append(allocator, token);
    }

    if (list.items.len == 0) return error.MissingConstraints;
    return list.toOwnedSlice(allocator);
}

fn isValidIdentifier(name: []const u8) bool {
    if (name.len == 0) return false;
    if (!isIdentStart(name[0])) return false;
    for (name[1..]) |c| if (!isIdentContinue(c)) return false;
    return true;
}

fn isIdentStart(c: u8) bool {
    return (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or c == '_';
}

fn isIdentContinue(c: u8) bool {
    return isIdentStart(c) or (c >= '0' and c <= '9');
}

fn appendLine(out: *std.ArrayList(u8), allocator: std.mem.Allocator, text: []const u8) !void {
    try out.appendSlice(allocator, text);
    try out.appendSlice(allocator, "\n");
}

fn appendSlice(out: *std.ArrayList(u8), allocator: std.mem.Allocator, text: []const u8) !void {
    try out.appendSlice(allocator, text);
}

fn appendFmt(out: *std.ArrayList(u8), allocator: std.mem.Allocator, comptime fmt: []const u8, args: anytype) !void {
    const rendered = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(rendered);
    try out.appendSlice(allocator, rendered);
}

fn printUsage(writer: anytype) !void {
    try writer.writeAll(
        \\Usage:
        \\  zig run constraint-test-generator.zig -- --constraints c1,c2 [options]
        \\
        \\Options:
        \\  --constraints <csv>       Comma-separated constraint ids (required).
        \\  --out <path>              Write to file (use '-' for stdout).
        \\  --suite <name>            Suite name prefix for tests (default: Constraints).
        \\  --harness-import <path>   Path to harness import (default: harness.zig).
        \\  --harness-name <name>     Identifier used for harness import (default: harness).
        \\  --proof-fn <ident>        Proof function (default: <harness-name>.requireProofForConstraint).
        \\  --constraint-type <ident> Constraint enum type (default: <harness-name>.ConstraintId).
        \\  --negative-only           Emit only negative tests.
        \\  --positive-only           Emit only positive tests.
        \\  --help                    Show this help.
        \\
        \\Notes:
        \\  Proof functions must accept (proof, constraint_id).
        \\  The generated tests fail by default to enforce TDD. Replace the TODOs.
        \\
    );
}
